### ISSUE TITLE
Errors on 2.3.0 and @next

### ISSUE THREAD

**Issue by coltcook** [NativeScript/sample-android-extend#3]
This example works fine with tns-core-modules 2.2.1 and tns-android 2.2.0, but if you upgrade those to current (2.3.0) or @next (tns-core-modules 2.5.0-2016-11-03-4657 and tns-android 2.5.0-next-2016-11-03-1349).

On 2.3.0 the app continually crashes when loaded in the emulator.

On @next, there is an "application.android already initialized" error.

**Comment by dlucidone** [comment]
It is still not fixed

**Comment by priyangamani** [comment]
Apps still crash

**Comment by tmandekic** [comment]
still crashing.

**Comment by priyangamani** [comment]
Try to use this ...  tns platform add android@next.

**Comment by vchimev** [comment]
Hey Guys,

The sample was updated to NativeScript@4.1. Please open a new issue if you experience any problems.

Thanks,
